### ISSUE TITLE
custom meta tags for bill/person/committee/event pages

### ISSUE THREAD

**Issue by cathydeng** [datamade/django-councilmatic#1]
currently all pages on the website have the same meta tags (from base.html) - we should have a better way to set custom meta info, for better SEO & better rich snippets

**Comment by cathydeng** [comment]
seo improvements:
- [ ] add bill abstract/description to bill meta desc (& make short version for twitter)
- [ ] add committee desc to committee meta desc where available (& make short version for twitter)
- [ ] custom fb title & twitter title for bill, person, committee, event
- [ ] use headshot for person meta photo, where available

**Comment by cathydeng** [comment]
closed via 3ae7eaafdae2eb6184c866dddf08c52f0335797f
